/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BackgammonRouteImport } from './routes/backgammon'
import { Route as BattleshipRouteImport } from './routes/battleship'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CrazyEightsRouteImport } from './routes/crazy-eights'
import { Route as CribbageRouteImport } from './routes/cribbage'
import { Route as FarkleRouteImport } from './routes/farkle'
import { Route as FreecellRouteImport } from './routes/freecell'
import { Route as FutureImprovementsRouteImport } from './routes/future-improvements'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReversiRouteImport } from './routes/reversi'
import { Route as SolitaireRouteImport } from './routes/solitaire'
import { Route as TrianglesRouteImport } from './routes/triangles'
import { Route as YahtzeeRouteImport } from './routes/yahtzee'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgammonRoute = BackgammonRouteImport.update({
  id: '/backgammon',
  path: '/backgammon',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleshipRoute = BattleshipRouteImport.update({
  id: '/battleship',
  path: '/battleship',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CrazyEightsRoute = CrazyEightsRouteImport.update({
  id: '/crazy-eights',
  path: '/crazy-eights',
  getParentRoute: () => rootRouteImport,
} as any)
const CribbageRoute = CribbageRouteImport.update({
  id: '/cribbage',
  path: '/cribbage',
  getParentRoute: () => rootRouteImport,
} as any)
const FarkleRoute = FarkleRouteImport.update({
  id: '/farkle',
  path: '/farkle',
  getParentRoute: () => rootRouteImport,
} as any)
const FreecellRoute = FreecellRouteImport.update({
  id: '/freecell',
  path: '/freecell',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureImprovementsRoute = FutureImprovementsRouteImport.update({
  id: '/future-improvements',
  path: '/future-improvements',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReversiRoute = ReversiRouteImport.update({
  id: '/reversi',
  path: '/reversi',
  getParentRoute: () => rootRouteImport,
} as any)
const SolitaireRoute = SolitaireRouteImport.update({
  id: '/solitaire',
  path: '/solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const TrianglesRoute = TrianglesRouteImport.update({
  id: '/triangles',
  path: '/triangles',
  getParentRoute: () => rootRouteImport,
} as any)
const YahtzeeRoute = YahtzeeRouteImport.update({
  id: '/yahtzee',
  path: '/yahtzee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backgammon': typeof BackgammonRoute
  '/battleship': typeof BattleshipRoute
  '/contact': typeof ContactRoute
  '/crazy-eights': typeof CrazyEightsRoute
  '/cribbage': typeof CribbageRoute
  '/farkle': typeof FarkleRoute
  '/freecell': typeof FreecellRoute
  '/future-improvements': typeof FutureImprovementsRoute
  '/privacy': typeof PrivacyRoute
  '/reversi': typeof ReversiRoute
  '/solitaire': typeof SolitaireRoute
  '/triangles': typeof TrianglesRoute
  '/yahtzee': typeof YahtzeeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backgammon': typeof BackgammonRoute
  '/battleship': typeof BattleshipRoute
  '/contact': typeof ContactRoute
  '/crazy-eights': typeof CrazyEightsRoute
  '/cribbage': typeof CribbageRoute
  '/farkle': typeof FarkleRoute
  '/freecell': typeof FreecellRoute
  '/future-improvements': typeof FutureImprovementsRoute
  '/privacy': typeof PrivacyRoute
  '/reversi': typeof ReversiRoute
  '/solitaire': typeof SolitaireRoute
  '/triangles': typeof TrianglesRoute
  '/yahtzee': typeof YahtzeeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backgammon': typeof BackgammonRoute
  '/battleship': typeof BattleshipRoute
  '/contact': typeof ContactRoute
  '/crazy-eights': typeof CrazyEightsRoute
  '/cribbage': typeof CribbageRoute
  '/farkle': typeof FarkleRoute
  '/freecell': typeof FreecellRoute
  '/future-improvements': typeof FutureImprovementsRoute
  '/privacy': typeof PrivacyRoute
  '/reversi': typeof ReversiRoute
  '/solitaire': typeof SolitaireRoute
  '/triangles': typeof TrianglesRoute
  '/yahtzee': typeof YahtzeeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backgammon'
    | '/battleship'
    | '/contact'
    | '/crazy-eights'
    | '/cribbage'
    | '/farkle'
    | '/freecell'
    | '/future-improvements'
    | '/privacy'
    | '/reversi'
    | '/solitaire'
    | '/triangles'
    | '/yahtzee'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backgammon'
    | '/battleship'
    | '/contact'
    | '/crazy-eights'
    | '/cribbage'
    | '/farkle'
    | '/freecell'
    | '/future-improvements'
    | '/privacy'
    | '/reversi'
    | '/solitaire'
    | '/triangles'
    | '/yahtzee'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backgammon'
    | '/battleship'
    | '/contact'
    | '/crazy-eights'
    | '/cribbage'
    | '/farkle'
    | '/freecell'
    | '/future-improvements'
    | '/privacy'
    | '/reversi'
    | '/solitaire'
    | '/triangles'
    | '/yahtzee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BackgammonRoute: typeof BackgammonRoute
  BattleshipRoute: typeof BattleshipRoute
  ContactRoute: typeof ContactRoute
  CrazyEightsRoute: typeof CrazyEightsRoute
  CribbageRoute: typeof CribbageRoute
  FarkleRoute: typeof FarkleRoute
  FreecellRoute: typeof FreecellRoute
  FutureImprovementsRoute: typeof FutureImprovementsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReversiRoute: typeof ReversiRoute
  SolitaireRoute: typeof SolitaireRoute
  TrianglesRoute: typeof TrianglesRoute
  YahtzeeRoute: typeof YahtzeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgammon': {
      id: '/backgammon'
      path: '/backgammon'
      fullPath: '/backgammon'
      preLoaderRoute: typeof BackgammonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battleship': {
      id: '/battleship'
      path: '/battleship'
      fullPath: '/battleship'
      preLoaderRoute: typeof BattleshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crazy-eights': {
      id: '/crazy-eights'
      path: '/crazy-eights'
      fullPath: '/crazy-eights'
      preLoaderRoute: typeof CrazyEightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cribbage': {
      id: '/cribbage'
      path: '/cribbage'
      fullPath: '/cribbage'
      preLoaderRoute: typeof CribbageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farkle': {
      id: '/farkle'
      path: '/farkle'
      fullPath: '/farkle'
      preLoaderRoute: typeof FarkleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freecell': {
      id: '/freecell'
      path: '/freecell'
      fullPath: '/freecell'
      preLoaderRoute: typeof FreecellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-improvements': {
      id: '/future-improvements'
      path: '/future-improvements'
      fullPath: '/future-improvements'
      preLoaderRoute: typeof FutureImprovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reversi': {
      id: '/reversi'
      path: '/reversi'
      fullPath: '/reversi'
      preLoaderRoute: typeof ReversiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solitaire': {
      id: '/solitaire'
      path: '/solitaire'
      fullPath: '/solitaire'
      preLoaderRoute: typeof SolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triangles': {
      id: '/triangles'
      path: '/triangles'
      fullPath: '/triangles'
      preLoaderRoute: typeof TrianglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yahtzee': {
      id: '/yahtzee'
      path: '/yahtzee'
      fullPath: '/yahtzee'
      preLoaderRoute: typeof YahtzeeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BackgammonRoute: BackgammonRoute,
  BattleshipRoute: BattleshipRoute,
  ContactRoute: ContactRoute,
  CrazyEightsRoute: CrazyEightsRoute,
  CribbageRoute: CribbageRoute,
  FarkleRoute: FarkleRoute,
  FreecellRoute: FreecellRoute,
  FutureImprovementsRoute: FutureImprovementsRoute,
  PrivacyRoute: PrivacyRoute,
  ReversiRoute: ReversiRoute,
  SolitaireRoute: SolitaireRoute,
  TrianglesRoute: TrianglesRoute,
  YahtzeeRoute: YahtzeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
