-- A simple, append-only visitor log. Each row is one recorded visit;
-- the visitor count is the number of rows.
CREATE TABLE public.site_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visited_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT ON public.site_visits TO anon;
GRANT SELECT, INSERT ON public.site_visits TO authenticated;
GRANT ALL ON public.site_visits TO service_role;

ALTER TABLE public.site_visits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read the visit count"
  ON public.site_visits FOR SELECT USING (true);

CREATE POLICY "Anyone can record a visit"
  ON public.site_visits FOR INSERT WITH CHECK (true);
